name: helloworld

on:
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Do helloworld
        uses: dagger/dagger-for-github@v2
        with:
          version: 0.2
          cmds: |
            project update
            do hello --log-format=plain
